name: Test Runner Monitoring

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Show runner info
        run: |
          echo "Runner is working!"
          echo "Hostname: $(hostname)"
          echo "Current time: $(date)"
          
      - name: Simulate work
        run: |
          echo "Simulating a 30-second job..."
          sleep 30
          echo "Job completed!"
